version: '3.8'

services:

  laravel-php:
    image: php:8.3-fpm-laravel
    build:
      context: ./php
    restart: unless-stopped
    tty: true
    volumes:
      - ./php/.bash_aliases:/root/.bash_aliases
      - ./php/conf.d/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
      - ./src:/var/www/html
    networks:
      - dockers-network

  laravel-nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - 1234:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./src:/var/www/html
    networks:
      - dockers-network

# Networks
networks:
  dockers-network:
    driver: bridge
